### ISSUE TITLE
请教一下配置文件的用法

### ISSUE THREAD

**Issue by recall704** [codeskyblue/gosuv#19]
你好，我在使用的时候对这个配置文件非常困惑， 请问下 server_url 是什么意思？

```
server:
  httpauth:
    enabled: false
    username: uu
    password: pp
  addr: :11313
client:
  server_url: http://localhost:11313
```

Thank you, have a good day!
